remote_db:
  ENGINE: django.db.backends.mysql
  NAME: meghnachakra2000$habit_tracker_db
  USER: meghnachakra2000
  PASSWORD: zen1357$230vio
  HOST: meghnachakra2000.mysql.pythonanywhere-services.com

local_db:
  ENGINE: django.db.backends.postgresql
  NAME: habit_db
  USER: postgres
  PASSWORD: maggi2000
  HOST: 127.0.0.1
